
#include "sdkconfig.h"

// Following values can be set by menuconfig or entered here
#define WIRE_PORT0_I2C_SCL_GPIO     CONFIG_WIRE_PORT0_I2C_SCL_GPIO
#define WIRE_PORT0_I2C_SDA_GPIO     CONFIG_WIRE_PORT0_I2C_SDA_GPIO
#define WIRE_PORT0_CLOCK_SPEED      CONFIG_WIRE_PORT0_CLOCK_SPEED
#define WIRE_PORT1_I2C_SCL_GPIO     CONFIG_WIRE_PORT1_I2C_SCL_GPIO
#define WIRE_PORT1_I2C_SDA_GPIO     CONFIG_WIRE_PORT1_I2C_SDA_GPIO
#define WIRE_PORT1_CLOCK_SPEED      CONFIG_WIRE_PORT1_CLOCK_SPEED
